import { FormikHelpers } from 'formik';
import AuthFooter from '../../components/AuthHeader/AuthFooter';
import AuthWrapper from '../../components/ReusableComponents/AuthWrapper';
import { useAuth } from '../../context/useAuthContext';
import { useSnackBar } from '../../context/useSnackbarContext';
import login from '../../helpers/APICalls/login';
import LoginForm from './LoginForm/LoginForm';
import useStyles from './useStyles';

export default function Login(): JSX.Element {
  const classes = useStyles();
  const { updateLoginContext } = useAuth();
  const { updateSnackBarMessage } = useSnackBar();

  const handleSubmit = (
    { email, password }: { email: string; password: string },
    { setSubmitting }: FormikHelpers<{ email: string; password: string }>,
  ) => {
    login(email, password).then((data) => {
      if (data.error) {
        setSubmitting(false);
        updateSnackBarMessage(data.error.message);
      } else if (data.success) {
        updateLoginContext(data.success);
      } else {
        // should not get here from backend but this catch is for an unknown issue
        console.error({ data });

        setSubmitting(false);
        updateSnackBarMessage('An unexpected error occurred. Please try again');
      }
    });
  };

  return (
    <AuthWrapper>
      <LoginForm handleSubmit={handleSubmit} />
      <AuthFooter linkTo="signup" asideText="I do not have an account" btnText="sign up" />
    </AuthWrapper>
  );
}
